/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectmanagment;

/**
 *
 * @author evwil0771
 */
public class ProjectManagment extends javax.swing.JFrame {

    /**
     * Creates new form ProjectManagment
     */
    public ProjectManagment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1Group = new javax.swing.ButtonGroup();
        q2Group = new javax.swing.ButtonGroup();
        q3Group = new javax.swing.ButtonGroup();
        q4Group = new javax.swing.ButtonGroup();
        q5Group = new javax.swing.ButtonGroup();
        q6Group = new javax.swing.ButtonGroup();
        q7Group = new javax.swing.ButtonGroup();
        q8Group = new javax.swing.ButtonGroup();
        q9Group = new javax.swing.ButtonGroup();
        q10Group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        q1Lbl = new javax.swing.JLabel();
        a1Btn = new javax.swing.JRadioButton();
        a2Btn = new javax.swing.JRadioButton();
        a3Btn = new javax.swing.JRadioButton();
        q2Lbl = new javax.swing.JLabel();
        a1Btn2 = new javax.swing.JRadioButton();
        a2Btn2 = new javax.swing.JRadioButton();
        a3Btn2 = new javax.swing.JRadioButton();
        q3Lbl = new javax.swing.JLabel();
        a1Btn3 = new javax.swing.JRadioButton();
        a2Btn3 = new javax.swing.JRadioButton();
        a3Btn3 = new javax.swing.JRadioButton();
        q4Lbl = new javax.swing.JLabel();
        a1Btn4 = new javax.swing.JRadioButton();
        a2Btn4 = new javax.swing.JRadioButton();
        a3Btn4 = new javax.swing.JRadioButton();
        q5Lbl = new javax.swing.JLabel();
        a1Btn5 = new javax.swing.JRadioButton();
        a2Btn5 = new javax.swing.JRadioButton();
        a3Btn5 = new javax.swing.JRadioButton();
        q9Lbl = new javax.swing.JLabel();
        a1Btn7 = new javax.swing.JRadioButton();
        a2Btn7 = new javax.swing.JRadioButton();
        a3Btn7 = new javax.swing.JRadioButton();
        a3Btn1 = new javax.swing.JRadioButton();
        q10Lbl = new javax.swing.JLabel();
        a1Btn8 = new javax.swing.JRadioButton();
        a2Btn8 = new javax.swing.JRadioButton();
        q7Lbl = new javax.swing.JLabel();
        a3Btn8 = new javax.swing.JRadioButton();
        a1Btn9 = new javax.swing.JRadioButton();
        a2Btn9 = new javax.swing.JRadioButton();
        a3Btn9 = new javax.swing.JRadioButton();
        q8Lbl = new javax.swing.JLabel();
        a1Btn10 = new javax.swing.JRadioButton();
        q6Lbl = new javax.swing.JLabel();
        a1Btn1 = new javax.swing.JRadioButton();
        a2Btn1 = new javax.swing.JRadioButton();
        a2Btn10 = new javax.swing.JRadioButton();
        a3Btn10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        titleLbl.setText("Project Managment Quiz");

        q1Lbl.setText("q1");

        q1Group.add(a1Btn);
        a1Btn.setText("jRadioButton1");
        a1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1BtnActionPerformed(evt);
            }
        });

        q1Group.add(a2Btn);
        a2Btn.setText("jRadioButton1");

        q1Group.add(a3Btn);
        a3Btn.setText("jRadioButton1");

        q2Lbl.setText("q2");

        q2Group.add(a1Btn2);
        a1Btn2.setText("jRadioButton1");

        q2Group.add(a2Btn2);
        a2Btn2.setText("jRadioButton1");

        q2Group.add(a3Btn2);
        a3Btn2.setText("jRadioButton1");

        q3Lbl.setText("q3");

        q3Group.add(a1Btn3);
        a1Btn3.setText("jRadioButton1");

        q3Group.add(a2Btn3);
        a2Btn3.setText("jRadioButton1");

        q3Group.add(a3Btn3);
        a3Btn3.setText("jRadioButton1");

        q4Lbl.setText("q4");

        q4Group.add(a1Btn4);
        a1Btn4.setText("jRadioButton1");

        q4Group.add(a2Btn4);
        a2Btn4.setText("jRadioButton1");

        q4Group.add(a3Btn4);
        a3Btn4.setText("jRadioButton1");

        q5Lbl.setText("q5");

        q5Group.add(a1Btn5);
        a1Btn5.setText("jRadioButton1");

        q5Group.add(a2Btn5);
        a2Btn5.setText("jRadioButton1");

        q5Group.add(a3Btn5);
        a3Btn5.setText("jRadioButton1");

        q9Lbl.setText("q9");

        q9Group.add(a1Btn7);
        a1Btn7.setText("jRadioButton1");

        q9Group.add(a2Btn7);
        a2Btn7.setText("jRadioButton1");

        q9Group.add(a3Btn7);
        a3Btn7.setText("jRadioButton1");

        q6Group.add(a3Btn1);
        a3Btn1.setText("jRadioButton1");

        q10Lbl.setText("q10");

        q10Group.add(a1Btn8);
        a1Btn8.setText("jRadioButton1");

        q10Group.add(a2Btn8);
        a2Btn8.setText("jRadioButton1");

        q7Lbl.setText("q7");

        q10Group.add(a3Btn8);
        a3Btn8.setText("jRadioButton1");

        q7Group.add(a1Btn9);
        a1Btn9.setText("jRadioButton1");

        q7Group.add(a2Btn9);
        a2Btn9.setText("jRadioButton1");

        q7Group.add(a3Btn9);
        a3Btn9.setText("jRadioButton1");

        q8Lbl.setText("q8");

        q8Group.add(a1Btn10);
        a1Btn10.setText("jRadioButton1");

        q6Lbl.setText("q6");

        q6Group.add(a1Btn1);
        a1Btn1.setText("jRadioButton1");
        a1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn1ActionPerformed(evt);
            }
        });

        q6Group.add(a2Btn1);
        a2Btn1.setText("jRadioButton1");

        q8Group.add(a2Btn10);
        a2Btn10.setText("jRadioButton1");

        q8Group.add(a3Btn10);
        a3Btn10.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q3Lbl)
                                .addGap(69, 69, 69)
                                .addComponent(a1Btn3)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3Btn3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q4Lbl)
                                .addGap(69, 69, 69)
                                .addComponent(a1Btn4)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3Btn4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q5Lbl)
                                .addGap(69, 69, 69)
                                .addComponent(a1Btn5)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3Btn5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q6Lbl)
                                    .addComponent(q7Lbl))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn9)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a3Btn9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn1)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn1)
                                        .addGap(18, 18, 18)
                                        .addComponent(a3Btn1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q8Lbl)
                                .addGap(69, 69, 69)
                                .addComponent(a1Btn10)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3Btn10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q9Lbl)
                                    .addComponent(q10Lbl))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn8)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn8)
                                        .addGap(18, 18, 18)
                                        .addComponent(a3Btn8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn7)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a3Btn7))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(titleLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q1Lbl)
                                    .addComponent(q2Lbl))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn2)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a3Btn2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(a3Btn)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1Lbl)
                    .addComponent(a1Btn)
                    .addComponent(a2Btn)
                    .addComponent(a3Btn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2Lbl)
                    .addComponent(a1Btn2)
                    .addComponent(a2Btn2)
                    .addComponent(a3Btn2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3Lbl)
                    .addComponent(a1Btn3)
                    .addComponent(a2Btn3)
                    .addComponent(a3Btn3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4Lbl)
                    .addComponent(a1Btn4)
                    .addComponent(a2Btn4)
                    .addComponent(a3Btn4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5Lbl)
                    .addComponent(a1Btn5)
                    .addComponent(a2Btn5)
                    .addComponent(a3Btn5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6Lbl)
                    .addComponent(a1Btn1)
                    .addComponent(a2Btn1)
                    .addComponent(a3Btn1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7Lbl)
                    .addComponent(a1Btn9)
                    .addComponent(a2Btn9)
                    .addComponent(a3Btn9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8Lbl)
                    .addComponent(a1Btn10)
                    .addComponent(a2Btn10)
                    .addComponent(a3Btn10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9Lbl)
                    .addComponent(a1Btn7)
                    .addComponent(a2Btn7)
                    .addComponent(a3Btn7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10Lbl)
                    .addComponent(a1Btn8)
                    .addComponent(a2Btn8)
                    .addComponent(a3Btn8))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1BtnActionPerformed

    private void a1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectManagment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1Btn;
    private javax.swing.JRadioButton a1Btn1;
    private javax.swing.JRadioButton a1Btn10;
    private javax.swing.JRadioButton a1Btn2;
    private javax.swing.JRadioButton a1Btn3;
    private javax.swing.JRadioButton a1Btn4;
    private javax.swing.JRadioButton a1Btn5;
    private javax.swing.JRadioButton a1Btn7;
    private javax.swing.JRadioButton a1Btn8;
    private javax.swing.JRadioButton a1Btn9;
    private javax.swing.JRadioButton a2Btn;
    private javax.swing.JRadioButton a2Btn1;
    private javax.swing.JRadioButton a2Btn10;
    private javax.swing.JRadioButton a2Btn2;
    private javax.swing.JRadioButton a2Btn3;
    private javax.swing.JRadioButton a2Btn4;
    private javax.swing.JRadioButton a2Btn5;
    private javax.swing.JRadioButton a2Btn7;
    private javax.swing.JRadioButton a2Btn8;
    private javax.swing.JRadioButton a2Btn9;
    private javax.swing.JRadioButton a3Btn;
    private javax.swing.JRadioButton a3Btn1;
    private javax.swing.JRadioButton a3Btn10;
    private javax.swing.JRadioButton a3Btn2;
    private javax.swing.JRadioButton a3Btn3;
    private javax.swing.JRadioButton a3Btn4;
    private javax.swing.JRadioButton a3Btn5;
    private javax.swing.JRadioButton a3Btn7;
    private javax.swing.JRadioButton a3Btn8;
    private javax.swing.JRadioButton a3Btn9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup q10Group;
    private javax.swing.JLabel q10Lbl;
    private javax.swing.ButtonGroup q1Group;
    private javax.swing.JLabel q1Lbl;
    private javax.swing.ButtonGroup q2Group;
    private javax.swing.JLabel q2Lbl;
    private javax.swing.ButtonGroup q3Group;
    private javax.swing.JLabel q3Lbl;
    private javax.swing.ButtonGroup q4Group;
    private javax.swing.JLabel q4Lbl;
    private javax.swing.ButtonGroup q5Group;
    private javax.swing.JLabel q5Lbl;
    private javax.swing.ButtonGroup q6Group;
    private javax.swing.JLabel q6Lbl;
    private javax.swing.ButtonGroup q7Group;
    private javax.swing.JLabel q7Lbl;
    private javax.swing.ButtonGroup q8Group;
    private javax.swing.JLabel q8Lbl;
    private javax.swing.ButtonGroup q9Group;
    private javax.swing.JLabel q9Lbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
