/**
 * Form for the quiz with the radio buttons
 */
package projectmanagment;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author evwil0771
 */
public class QuizForm extends javax.swing.JFrame {

    MainMenu mainMenuWindow;

    //Store the questions
    ArrayList<Question> data = DataLoader.readQuestions();
    //Store a shallow copy of the buttons in an arraylist
    ArrayList<javax.swing.JLabel> questionLabels = new ArrayList<>();
    //Store the radioButtons
    ArrayList<ArrayList<javax.swing.JRadioButton>> radioButtons = new ArrayList<>();

    //Store the scores to output
    ArrayList<javax.swing.JLabel> scoreTexArrayList = new ArrayList<>();

    //Store the notes text fields in an arraylist
    ArrayList<javax.swing.JLabel> notesArrayList = new ArrayList<>();

    /**
     * Creates new form ProjectManagment
     */
    public QuizForm(MainMenu m) {
        initComponents();
        mainMenuWindow = m;

        //Set the defaults for a blank form
        setDefaults();

        //Create the form when the window is initialized
        //show a guide message at the first time the program starts
        JOptionPane.showMessageDialog(null, "Steps for completing quiz: \n1, Check each question at the front of each row, and check your answer with the possible answer behind the question(radio buttons) "
                + "\n2, Select the possible answer you want to choose, and contuine 1-2 steps though the whole quiz. "
                + "\n3, After you checked each answer and all answer have at least 1 answer is choosen in each question, press submit button to hand in your answer. "
                + "\n4, You can see your final score and wrong answers after you click the submit button, and study note for each quetsion will be provide at the right side of the pannel. ");
    }

    /**
     * Set the defaults for a new blank form
     */
    private void setDefaults() {
        //Create the form when the window is initialized
        writeQuestion();
        writeAnswer();
        loadScoreText();
        loadNotes();
        refreshScore();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1Group = new javax.swing.ButtonGroup();
        q2Group = new javax.swing.ButtonGroup();
        q3Group = new javax.swing.ButtonGroup();
        q4Group = new javax.swing.ButtonGroup();
        q5Group = new javax.swing.ButtonGroup();
        q6Group = new javax.swing.ButtonGroup();
        q7Group = new javax.swing.ButtonGroup();
        q8Group = new javax.swing.ButtonGroup();
        q9Group = new javax.swing.ButtonGroup();
        q10Group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        q1Lbl = new javax.swing.JLabel();
        a1Btn1 = new javax.swing.JRadioButton();
        a2Btn1 = new javax.swing.JRadioButton();
        a3Btn1 = new javax.swing.JRadioButton();
        a4Btn1 = new javax.swing.JRadioButton();
        q2Lbl = new javax.swing.JLabel();
        a1Btn2 = new javax.swing.JRadioButton();
        a2Btn2 = new javax.swing.JRadioButton();
        a3Btn2 = new javax.swing.JRadioButton();
        a4Btn2 = new javax.swing.JRadioButton();
        q3Lbl = new javax.swing.JLabel();
        a1Btn3 = new javax.swing.JRadioButton();
        a2Btn3 = new javax.swing.JRadioButton();
        a3Btn3 = new javax.swing.JRadioButton();
        q4Lbl = new javax.swing.JLabel();
        a1Btn4 = new javax.swing.JRadioButton();
        a2Btn4 = new javax.swing.JRadioButton();
        a3Btn4 = new javax.swing.JRadioButton();
        q5Lbl = new javax.swing.JLabel();
        a1Btn5 = new javax.swing.JRadioButton();
        a2Btn5 = new javax.swing.JRadioButton();
        a3Btn5 = new javax.swing.JRadioButton();
        q9Lbl = new javax.swing.JLabel();
        a1Btn7 = new javax.swing.JRadioButton();
        a2Btn7 = new javax.swing.JRadioButton();
        a3Btn7 = new javax.swing.JRadioButton();
        a3Btn6 = new javax.swing.JRadioButton();
        q10Lbl = new javax.swing.JLabel();
        a1Btn8 = new javax.swing.JRadioButton();
        a2Btn8 = new javax.swing.JRadioButton();
        q7Lbl = new javax.swing.JLabel();
        a3Btn8 = new javax.swing.JRadioButton();
        a1Btn9 = new javax.swing.JRadioButton();
        a2Btn9 = new javax.swing.JRadioButton();
        a3Btn9 = new javax.swing.JRadioButton();
        q8Lbl = new javax.swing.JLabel();
        a1Btn10 = new javax.swing.JRadioButton();
        q6Lbl = new javax.swing.JLabel();
        a1Btn6 = new javax.swing.JRadioButton();
        a2Btn6 = new javax.swing.JRadioButton();
        a2Btn10 = new javax.swing.JRadioButton();
        a3Btn10 = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        a4Btn3 = new javax.swing.JRadioButton();
        a4Btn4 = new javax.swing.JRadioButton();
        a4Btn5 = new javax.swing.JRadioButton();
        a4Btn6 = new javax.swing.JRadioButton();
        a4Btn7 = new javax.swing.JRadioButton();
        a4Btn8 = new javax.swing.JRadioButton();
        a4Btn9 = new javax.swing.JRadioButton();
        a4Btn10 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        score6 = new javax.swing.JLabel();
        score7 = new javax.swing.JLabel();
        score8 = new javax.swing.JLabel();
        score9 = new javax.swing.JLabel();
        score10 = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        note2 = new javax.swing.JLabel();
        note3 = new javax.swing.JLabel();
        note4 = new javax.swing.JLabel();
        note5 = new javax.swing.JLabel();
        note6 = new javax.swing.JLabel();
        note7 = new javax.swing.JLabel();
        note8 = new javax.swing.JLabel();
        note9 = new javax.swing.JLabel();
        note10 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        restart = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        titleLbl.setText("Project Managment Quiz");

        q1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q1Lbl.setText("q1");

        q1Group.add(a1Btn1);
        a1Btn1.setText("jRadioButton1");
        a1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn1ActionPerformed(evt);
            }
        });

        q1Group.add(a2Btn1);
        a2Btn1.setText("jRadioButton1");

        q1Group.add(a3Btn1);
        a3Btn1.setText("jRadioButton1");

        q1Group.add(a4Btn1);
        a4Btn1.setText("jRadioButton1");

        q2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q2Lbl.setText("q2");

        q2Group.add(a1Btn2);
        a1Btn2.setText("jRadioButton1");

        q2Group.add(a2Btn2);
        a2Btn2.setText("jRadioButton1");

        q2Group.add(a3Btn2);
        a3Btn2.setText("jRadioButton1");

        q2Group.add(a4Btn2);
        a4Btn2.setText("jRadioButton1");

        q3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q3Lbl.setText("q3");

        q3Group.add(a1Btn3);
        a1Btn3.setText("jRadioButton1");

        q3Group.add(a2Btn3);
        a2Btn3.setText("jRadioButton1");

        q3Group.add(a3Btn3);
        a3Btn3.setText("jRadioButton1");

        q4Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q4Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q4Lbl.setText("q4");

        q4Group.add(a1Btn4);
        a1Btn4.setText("jRadioButton1");

        q4Group.add(a2Btn4);
        a2Btn4.setText("jRadioButton1");

        q4Group.add(a3Btn4);
        a3Btn4.setText("jRadioButton1");

        q5Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q5Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q5Lbl.setText("q5");

        q5Group.add(a1Btn5);
        a1Btn5.setText("jRadioButton1");

        q5Group.add(a2Btn5);
        a2Btn5.setText("jRadioButton1");

        q5Group.add(a3Btn5);
        a3Btn5.setText("jRadioButton1");

        q9Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q9Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q9Lbl.setText("q9");

        q7Group.add(a1Btn7);
        a1Btn7.setText("jRadioButton1");
        a1Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn7ActionPerformed(evt);
            }
        });

        q7Group.add(a2Btn7);
        a2Btn7.setText("jRadioButton1");

        q7Group.add(a3Btn7);
        a3Btn7.setText("jRadioButton1");

        q6Group.add(a3Btn6);
        a3Btn6.setText("jRadioButton1");

        q10Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q10Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q10Lbl.setText("q10");

        q8Group.add(a1Btn8);
        a1Btn8.setText("jRadioButton1");

        q8Group.add(a2Btn8);
        a2Btn8.setText("jRadioButton1");

        q7Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q7Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q7Lbl.setText("q7");

        q8Group.add(a3Btn8);
        a3Btn8.setText("jRadioButton1");

        q9Group.add(a1Btn9);
        a1Btn9.setText("jRadioButton1");

        q9Group.add(a2Btn9);
        a2Btn9.setText("jRadioButton1");

        q9Group.add(a3Btn9);
        a3Btn9.setText("jRadioButton1");

        q8Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q8Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q8Lbl.setText("q8");

        q10Group.add(a1Btn10);
        a1Btn10.setText("jRadioButton1");

        q6Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        q6Lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        q6Lbl.setText("q6");

        q6Group.add(a1Btn6);
        a1Btn6.setText("jRadioButton1");
        a1Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn6ActionPerformed(evt);
            }
        });

        q6Group.add(a2Btn6);
        a2Btn6.setText("jRadioButton1");

        q10Group.add(a2Btn10);
        a2Btn10.setText("jRadioButton1");

        q10Group.add(a3Btn10);
        a3Btn10.setText("jRadioButton1");

        backBtn.setText("Back To Main Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        q3Group.add(a4Btn3);
        a4Btn3.setText("jRadioButton1");

        q4Group.add(a4Btn4);
        a4Btn4.setText("jRadioButton1");

        q5Group.add(a4Btn5);
        a4Btn5.setText("jRadioButton1");

        q6Group.add(a4Btn6);
        a4Btn6.setText("jRadioButton1");

        q7Group.add(a4Btn7);
        a4Btn7.setText("jRadioButton1");

        q8Group.add(a4Btn8);
        a4Btn8.setText("jRadioButton1");

        q9Group.add(a4Btn9);
        a4Btn9.setText("jRadioButton1");

        q10Group.add(a4Btn10);
        a4Btn10.setText("jRadioButton1");

        submit.setText("Submit Quiz");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        score1.setText("jLabel1");

        score2.setText("jLabel1");

        score3.setText("jLabel1");

        score4.setText("jLabel1");

        score5.setText("jLabel1");

        score6.setText("jLabel1");

        score7.setText("jLabel1");

        score8.setText("jLabel1");

        score9.setText("jLabel1");

        score10.setText("jLabel1");

        note1.setText("jLabel1");

        note2.setText("jLabel1");

        note3.setText("jLabel1");

        note4.setText("jLabel1");

        note5.setText("jLabel1");

        note6.setText("jLabel1");

        note7.setText("jLabel1");

        note8.setText("jLabel1");

        note9.setText("jLabel1");

        note10.setText("jLabel1");

        total.setText("jLabel1");

        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(score2))
                            .addComponent(note1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn3)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn3)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn3)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn3)
                                .addGap(18, 18, 18)
                                .addComponent(score3))
                            .addComponent(note2)
                            .addComponent(note3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn6)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn6)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn6)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn6)
                                .addGap(18, 18, 18)
                                .addComponent(score6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn7)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn7)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn7)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn7)
                                .addGap(18, 18, 18)
                                .addComponent(score7))
                            .addComponent(note6)
                            .addComponent(note7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn5)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn5)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn5)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn5)
                                .addGap(18, 18, 18)
                                .addComponent(score5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn4)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn4)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn4)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn4)
                                .addGap(18, 18, 18)
                                .addComponent(score4))
                            .addComponent(note4)
                            .addComponent(note5)
                            .addComponent(q5Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q7Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn8)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn8)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn8)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn8)
                                .addGap(18, 18, 18)
                                .addComponent(score8))
                            .addComponent(note8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn9)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn9))
                                    .addComponent(note9))
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn9)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn9)
                                .addGap(18, 18, 18)
                                .addComponent(score9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn10)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn10)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn10)
                                .addGap(18, 18, 18)
                                .addComponent(a4Btn10)
                                .addGap(18, 18, 18)
                                .addComponent(score10))
                            .addComponent(note10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titleLbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a1Btn1)
                                        .addGap(18, 18, 18)
                                        .addComponent(a2Btn1)
                                        .addGap(18, 18, 18)
                                        .addComponent(a3Btn1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(a4Btn1)
                                        .addGap(18, 18, 18)
                                        .addComponent(score1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(total))))
                            .addComponent(q8Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q9Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q10Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q6Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q4Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(helpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restart)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(total))
                .addGap(9, 9, 9)
                .addComponent(q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn1)
                    .addComponent(a2Btn1)
                    .addComponent(a3Btn1)
                    .addComponent(a4Btn1)
                    .addComponent(score1))
                .addGap(7, 7, 7)
                .addComponent(note1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn2)
                    .addComponent(a2Btn2)
                    .addComponent(a3Btn2)
                    .addComponent(a4Btn2)
                    .addComponent(score2))
                .addGap(5, 5, 5)
                .addComponent(note2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn3)
                    .addComponent(a2Btn3)
                    .addComponent(a3Btn3)
                    .addComponent(a4Btn3)
                    .addComponent(score3))
                .addGap(7, 7, 7)
                .addComponent(note3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q4Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn4)
                    .addComponent(a2Btn4)
                    .addComponent(a3Btn4)
                    .addComponent(a4Btn4)
                    .addComponent(score4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note4)
                .addGap(13, 13, 13)
                .addComponent(q5Lbl)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn5)
                    .addComponent(a2Btn5)
                    .addComponent(a3Btn5)
                    .addComponent(a4Btn5)
                    .addComponent(score5))
                .addGap(7, 7, 7)
                .addComponent(note5)
                .addGap(18, 18, 18)
                .addComponent(q6Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn6)
                    .addComponent(a2Btn6)
                    .addComponent(a3Btn6)
                    .addComponent(a4Btn6)
                    .addComponent(score6))
                .addGap(5, 5, 5)
                .addComponent(note6)
                .addGap(18, 18, 18)
                .addComponent(q7Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn7)
                    .addComponent(a2Btn7)
                    .addComponent(a3Btn7)
                    .addComponent(a4Btn7)
                    .addComponent(score7))
                .addGap(5, 5, 5)
                .addComponent(note7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q8Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Btn8)
                    .addComponent(a2Btn8)
                    .addComponent(a3Btn8)
                    .addComponent(a4Btn8)
                    .addComponent(score8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q9Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a1Btn9)
                        .addComponent(a2Btn9)
                        .addComponent(a4Btn9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(score9)
                        .addComponent(a3Btn9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q10Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a1Btn10)
                        .addComponent(a2Btn10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a3Btn10)
                        .addComponent(a4Btn10)
                        .addComponent(score10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note10)
                .addGap(14, 133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(submit)
                    .addComponent(restart)
                    .addComponent(helpButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //Store the total maximum for the quiz and the total the user got
        int completeTotal = 0;
        int currentTotal = 0;

        //Loop for each question
        for (int i = 0; i < data.size(); i++) {
            //Save the answer to the question
            String answer = data.get(i).getTrueAns();

            //Add 1 to the total maximum for each question
            completeTotal++;

            //Store if the user got the question correct
            boolean gotCorrect = false;

            //Loop for all the radio buttons
            for (int j = 0; j < radioButtons.get(i).size(); j++) {

                //If j radio button was selected
                if (radioButtons.get(i).get(j).isSelected()) {
                    //Check if the selected radio button is equal to the answer
                    if (radioButtons.get(i).get(j).getText().equals(answer)) {

                        //Got answer correct
                        gotCorrect = true;
                        //Score correctly, give them a point
                        data.get(i).setScore(1);
                    }
                }
            }
            //If they got the question wrong
            if (gotCorrect == false) {
                //Set the score to 0
                data.get(i).setScore(0);
                //Show the notes
                notesArrayList.get(i).setVisible(true);
                notesArrayList.get(i).setText(data.get(i).getFeedback());
            }

            //Set the score counter to be visible
            scoreTexArrayList.get(i).setVisible(true);
            //output the score for the question
            scoreTexArrayList.get(i).setText(String.valueOf(data.get(i).getScore()) + "/1");

            currentTotal += data.get(i).getScore();
        }

        //Output the total
        total.setText(String.valueOf(currentTotal) + "/" + String.valueOf(completeTotal));
        total.setVisible(true);

    }//GEN-LAST:event_submitActionPerformed

    /**
     * Go back to the main menu
     *
     * @param evt
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        // Create Quiz Window
        //Quiz window frame is now visible
        mainMenuWindow.setVisible(true);

        //Set This Window to not be visible
        this.setVisible(false);

        //reset the quiz
        setDefaults();
    }//GEN-LAST:event_backBtnActionPerformed

    private void a1Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn6ActionPerformed

    private void a1Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn7ActionPerformed

    private void a1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn1ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        // TODO add your handling code here:
        setDefaults();
    }//GEN-LAST:event_restartActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        //let user check the guiding message again
        JOptionPane.showMessageDialog(null, "Steps for completing quiz: \n1, Check each question at the front of each row, and check your answer with the possible answer behind the question(radio buttons) "
                + "\n2, Select the possible answer you want to choose, and contuine 1-2 steps though the whole quiz. "
                + "\n3, After you checked each answer and all answer have at least 1 answer is choosen in each question, press submit button to hand in your answer. "
                + "\n4, You can see your final score and wrong answers after you click the submit button, and study note for each quetsion will be provide at the right side of the pannel. ");
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * Method that handles the output of the questions for each row
     */
    public void writeQuestion() {

        //Store a shallow copy of the buttons in an arraylist
        questionLabels = new ArrayList<>(Arrays.asList(q1Lbl, q2Lbl, q3Lbl, q4Lbl, q5Lbl, q6Lbl, q7Lbl, q8Lbl, q9Lbl, q10Lbl));

        //Save all the questions in an arraylist
        for (int i = 0; i < data.size(); i++) {
            //Store the question to be written
            String question = data.get(i).getQuestion();

            //Write the question
            questionLabels.get(i).setText(question);
        }
    }

    /**
     * Method that handles the output of the radio buttons with a semi random
     * order
     */
    public void writeAnswer() {

        //2d Arraylist for the radio button options
        radioButtons = new ArrayList<>(Arrays.asList(new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn1, a2Btn1, a3Btn1, a4Btn1)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn2, a2Btn2, a3Btn2, a4Btn2)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn3, a2Btn3, a3Btn3, a4Btn3)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn4, a2Btn4, a3Btn4, a4Btn4)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn5, a2Btn5, a3Btn5, a4Btn5)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn6, a2Btn6, a3Btn6, a4Btn6)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn7, a2Btn7, a3Btn7, a4Btn7)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn8, a2Btn8, a3Btn8, a4Btn8)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn9, a2Btn9, a3Btn9, a4Btn9)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn10, a2Btn10, a3Btn10, a4Btn10))));

        //Loop for each question
        for (int i = 0; i < data.size(); i++) {
            //Get a random number
            int random = randomNum(1, 4);

            //Assign the true answer semi randomly to a radio button
            switch (random) {
                case 1:
                    radioButtons.get(i).get(0).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(1).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(2).setText(data.get(i).getPossibleAns3());
                    radioButtons.get(i).get(3).setText(data.get(i).getTrueAns());
                    break;
                case 2:
                    radioButtons.get(i).get(0).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(1).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(2).setText(data.get(i).getTrueAns());
                    radioButtons.get(i).get(3).setText(data.get(i).getPossibleAns3());
                    break;
                case 3:
                    radioButtons.get(i).get(0).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(1).setText(data.get(i).getTrueAns());
                    radioButtons.get(i).get(2).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(3).setText(data.get(i).getPossibleAns3());
                    break;
                case 4:
                    radioButtons.get(i).get(0).setText(data.get(i).getTrueAns());
                    radioButtons.get(i).get(1).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(2).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(3).setText(data.get(i).getPossibleAns3());
                    break;
                default:
                    break;
            }

        }
    }

    /**
     * Load the score text labels in an arraylist
     */
    private void loadScoreText() {
        scoreTexArrayList = new ArrayList<>(Arrays.asList(score1, score2, score3, score4, score5, score6, score7, score8, score9, score10));

        //make all of them not visible
        for (int i = 0; i < scoreTexArrayList.size(); i++) {
            scoreTexArrayList.get(i).setVisible(false);
        }
    }

    /**
     * Load all the notes text labels in an arraylist
     */
    private void loadNotes() {
        notesArrayList = new ArrayList<>(Arrays.asList(note1, note2, note3, note4, note5, note6, note7, note8, note9, note10));

        //make all of them not visible
        for (int i = 0; i < notesArrayList.size(); i++) {
            notesArrayList.get(i).setVisible(false);
        }
    }

    /**
     * Make the score hidden
     */
    private void refreshScore() {
        total.setVisible(false);
    }

    /**
     * Generate a random number in a range
     *
     * @param min minimum value
     * @param max maximum value
     * @return random number in range
     */
    private int randomNum(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1Btn1;
    private javax.swing.JRadioButton a1Btn10;
    private javax.swing.JRadioButton a1Btn2;
    private javax.swing.JRadioButton a1Btn3;
    private javax.swing.JRadioButton a1Btn4;
    private javax.swing.JRadioButton a1Btn5;
    private javax.swing.JRadioButton a1Btn6;
    private javax.swing.JRadioButton a1Btn7;
    private javax.swing.JRadioButton a1Btn8;
    private javax.swing.JRadioButton a1Btn9;
    private javax.swing.JRadioButton a2Btn1;
    private javax.swing.JRadioButton a2Btn10;
    private javax.swing.JRadioButton a2Btn2;
    private javax.swing.JRadioButton a2Btn3;
    private javax.swing.JRadioButton a2Btn4;
    private javax.swing.JRadioButton a2Btn5;
    private javax.swing.JRadioButton a2Btn6;
    private javax.swing.JRadioButton a2Btn7;
    private javax.swing.JRadioButton a2Btn8;
    private javax.swing.JRadioButton a2Btn9;
    private javax.swing.JRadioButton a3Btn1;
    private javax.swing.JRadioButton a3Btn10;
    private javax.swing.JRadioButton a3Btn2;
    private javax.swing.JRadioButton a3Btn3;
    private javax.swing.JRadioButton a3Btn4;
    private javax.swing.JRadioButton a3Btn5;
    private javax.swing.JRadioButton a3Btn6;
    private javax.swing.JRadioButton a3Btn7;
    private javax.swing.JRadioButton a3Btn8;
    private javax.swing.JRadioButton a3Btn9;
    private javax.swing.JRadioButton a4Btn1;
    private javax.swing.JRadioButton a4Btn10;
    private javax.swing.JRadioButton a4Btn2;
    private javax.swing.JRadioButton a4Btn3;
    private javax.swing.JRadioButton a4Btn4;
    private javax.swing.JRadioButton a4Btn5;
    private javax.swing.JRadioButton a4Btn6;
    private javax.swing.JRadioButton a4Btn7;
    private javax.swing.JRadioButton a4Btn8;
    private javax.swing.JRadioButton a4Btn9;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel note1;
    private javax.swing.JLabel note10;
    private javax.swing.JLabel note2;
    private javax.swing.JLabel note3;
    private javax.swing.JLabel note4;
    private javax.swing.JLabel note5;
    private javax.swing.JLabel note6;
    private javax.swing.JLabel note7;
    private javax.swing.JLabel note8;
    private javax.swing.JLabel note9;
    private javax.swing.ButtonGroup q10Group;
    private javax.swing.JLabel q10Lbl;
    private javax.swing.ButtonGroup q1Group;
    private javax.swing.JLabel q1Lbl;
    private javax.swing.ButtonGroup q2Group;
    private javax.swing.JLabel q2Lbl;
    private javax.swing.ButtonGroup q3Group;
    private javax.swing.JLabel q3Lbl;
    private javax.swing.ButtonGroup q4Group;
    private javax.swing.JLabel q4Lbl;
    private javax.swing.ButtonGroup q5Group;
    private javax.swing.JLabel q5Lbl;
    private javax.swing.ButtonGroup q6Group;
    private javax.swing.JLabel q6Lbl;
    private javax.swing.ButtonGroup q7Group;
    private javax.swing.JLabel q7Lbl;
    private javax.swing.ButtonGroup q8Group;
    private javax.swing.JLabel q8Lbl;
    private javax.swing.ButtonGroup q9Group;
    private javax.swing.JLabel q9Lbl;
    private javax.swing.JButton restart;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score10;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    private javax.swing.JLabel score7;
    private javax.swing.JLabel score8;
    private javax.swing.JLabel score9;
    private javax.swing.JButton submit;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
