/**
 * Form for the quiz with the radio buttons
 */
package projectmanagment;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author evwil0771
 */
public class QuizForm extends javax.swing.JFrame {

    MainMenu mainMenuWindow;

    /**
     * Creates new form ProjectManagment
     */
    public QuizForm(MainMenu m) {
        initComponents();
        mainMenuWindow = m;
        
        //Create the form when the window is initialized
        writeQuestion();
        writeAnswer();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1Group = new javax.swing.ButtonGroup();
        q2Group = new javax.swing.ButtonGroup();
        q3Group = new javax.swing.ButtonGroup();
        q4Group = new javax.swing.ButtonGroup();
        q5Group = new javax.swing.ButtonGroup();
        q6Group = new javax.swing.ButtonGroup();
        q7Group = new javax.swing.ButtonGroup();
        q8Group = new javax.swing.ButtonGroup();
        q9Group = new javax.swing.ButtonGroup();
        q10Group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        q1Lbl = new javax.swing.JLabel();
        a1Btn1 = new javax.swing.JRadioButton();
        a2Btn1 = new javax.swing.JRadioButton();
        a3Btn1 = new javax.swing.JRadioButton();
        a4Btn1 = new javax.swing.JRadioButton();
        q2Lbl = new javax.swing.JLabel();
        a1Btn2 = new javax.swing.JRadioButton();
        a2Btn2 = new javax.swing.JRadioButton();
        a3Btn2 = new javax.swing.JRadioButton();
        a4Btn2 = new javax.swing.JRadioButton();
        q3Lbl = new javax.swing.JLabel();
        a1Btn3 = new javax.swing.JRadioButton();
        a2Btn3 = new javax.swing.JRadioButton();
        a3Btn3 = new javax.swing.JRadioButton();
        q4Lbl = new javax.swing.JLabel();
        a1Btn4 = new javax.swing.JRadioButton();
        a2Btn4 = new javax.swing.JRadioButton();
        a3Btn4 = new javax.swing.JRadioButton();
        q5Lbl = new javax.swing.JLabel();
        a1Btn5 = new javax.swing.JRadioButton();
        a2Btn5 = new javax.swing.JRadioButton();
        a3Btn5 = new javax.swing.JRadioButton();
        q9Lbl = new javax.swing.JLabel();
        a1Btn7 = new javax.swing.JRadioButton();
        a2Btn7 = new javax.swing.JRadioButton();
        a3Btn7 = new javax.swing.JRadioButton();
        a3Btn6 = new javax.swing.JRadioButton();
        q10Lbl = new javax.swing.JLabel();
        a1Btn8 = new javax.swing.JRadioButton();
        a2Btn8 = new javax.swing.JRadioButton();
        q7Lbl = new javax.swing.JLabel();
        a3Btn8 = new javax.swing.JRadioButton();
        a1Btn9 = new javax.swing.JRadioButton();
        a2Btn9 = new javax.swing.JRadioButton();
        a3Btn9 = new javax.swing.JRadioButton();
        q8Lbl = new javax.swing.JLabel();
        a1Btn10 = new javax.swing.JRadioButton();
        q6Lbl = new javax.swing.JLabel();
        a1Btn6 = new javax.swing.JRadioButton();
        a2Btn6 = new javax.swing.JRadioButton();
        a2Btn10 = new javax.swing.JRadioButton();
        a3Btn10 = new javax.swing.JRadioButton();
        feedBackFeild = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        a4Btn3 = new javax.swing.JRadioButton();
        a4Btn4 = new javax.swing.JRadioButton();
        a4Btn5 = new javax.swing.JRadioButton();
        a4Btn6 = new javax.swing.JRadioButton();
        a4Btn7 = new javax.swing.JRadioButton();
        a4Btn8 = new javax.swing.JRadioButton();
        a4Btn9 = new javax.swing.JRadioButton();
        a4Btn10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        titleLbl.setText("Project Managment Quiz");

        q1Lbl.setText("q1");

        q1Group.add(a1Btn1);
        a1Btn1.setText("jRadioButton1");
        a1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn1ActionPerformed(evt);
            }
        });

        q1Group.add(a2Btn1);
        a2Btn1.setText("jRadioButton1");

        q1Group.add(a3Btn1);
        a3Btn1.setText("jRadioButton1");

        q1Group.add(a4Btn1);
        a4Btn1.setText("jRadioButton1");

        q2Lbl.setText("q2");

        q2Group.add(a1Btn2);
        a1Btn2.setText("jRadioButton1");

        q2Group.add(a2Btn2);
        a2Btn2.setText("jRadioButton1");

        q2Group.add(a3Btn2);
        a3Btn2.setText("jRadioButton1");

        q2Group.add(a4Btn2);
        a4Btn2.setText("jRadioButton1");

        q3Lbl.setText("q3");

        q3Group.add(a1Btn3);
        a1Btn3.setText("jRadioButton1");

        q3Group.add(a2Btn3);
        a2Btn3.setText("jRadioButton1");

        q3Group.add(a3Btn3);
        a3Btn3.setText("jRadioButton1");

        q4Lbl.setText("q4");

        q4Group.add(a1Btn4);
        a1Btn4.setText("jRadioButton1");

        q4Group.add(a2Btn4);
        a2Btn4.setText("jRadioButton1");

        q4Group.add(a3Btn4);
        a3Btn4.setText("jRadioButton1");

        q5Lbl.setText("q5");

        q5Group.add(a1Btn5);
        a1Btn5.setText("jRadioButton1");

        q5Group.add(a2Btn5);
        a2Btn5.setText("jRadioButton1");

        q5Group.add(a3Btn5);
        a3Btn5.setText("jRadioButton1");

        q9Lbl.setText("q9");

        q7Group.add(a1Btn7);
        a1Btn7.setText("jRadioButton1");
        a1Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn7ActionPerformed(evt);
            }
        });

        q7Group.add(a2Btn7);
        a2Btn7.setText("jRadioButton1");

        q7Group.add(a3Btn7);
        a3Btn7.setText("jRadioButton1");

        q6Group.add(a3Btn6);
        a3Btn6.setText("jRadioButton1");

        q10Lbl.setText("q10");

        q8Group.add(a1Btn8);
        a1Btn8.setText("jRadioButton1");

        q8Group.add(a2Btn8);
        a2Btn8.setText("jRadioButton1");

        q7Lbl.setText("q7");

        q8Group.add(a3Btn8);
        a3Btn8.setText("jRadioButton1");

        q9Group.add(a1Btn9);
        a1Btn9.setText("jRadioButton1");

        q9Group.add(a2Btn9);
        a2Btn9.setText("jRadioButton1");

        q9Group.add(a3Btn9);
        a3Btn9.setText("jRadioButton1");

        q8Lbl.setText("q8");

        q10Group.add(a1Btn10);
        a1Btn10.setText("jRadioButton1");

        q6Lbl.setText("q6");

        q6Group.add(a1Btn6);
        a1Btn6.setText("jRadioButton1");
        a1Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1Btn6ActionPerformed(evt);
            }
        });

        q6Group.add(a2Btn6);
        a2Btn6.setText("jRadioButton1");

        q10Group.add(a2Btn10);
        a2Btn10.setText("jRadioButton1");

        q10Group.add(a3Btn10);
        a3Btn10.setText("jRadioButton1");

        feedBackFeild.setText("Feedback:");

        backBtn.setText("Back To Main Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        q3Group.add(a4Btn3);
        a4Btn3.setText("jRadioButton1");

        q4Group.add(a4Btn4);
        a4Btn4.setText("jRadioButton1");

        q5Group.add(a4Btn5);
        a4Btn5.setText("jRadioButton1");

        q6Group.add(a4Btn6);
        a4Btn6.setText("jRadioButton1");

        q7Group.add(a4Btn7);
        a4Btn7.setText("jRadioButton1");

        q8Group.add(a4Btn8);
        a4Btn8.setText("jRadioButton1");

        q9Group.add(a4Btn9);
        a4Btn9.setText("jRadioButton1");

        q10Group.add(a4Btn10);
        a4Btn10.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1Lbl)
                            .addComponent(q2Lbl))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3Btn2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn1)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn1)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a4Btn1)
                            .addComponent(a4Btn2)))
                    .addComponent(q8Lbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q3Lbl)
                        .addGap(69, 69, 69)
                        .addComponent(a1Btn3)
                        .addGap(18, 18, 18)
                        .addComponent(a2Btn3)
                        .addGap(18, 18, 18)
                        .addComponent(a3Btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a4Btn3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q4Lbl)
                        .addGap(69, 69, 69)
                        .addComponent(a1Btn4)
                        .addGap(18, 18, 18)
                        .addComponent(a2Btn4)
                        .addGap(18, 18, 18)
                        .addComponent(a3Btn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a4Btn4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q5Lbl)
                        .addGap(69, 69, 69)
                        .addComponent(a1Btn5)
                        .addGap(18, 18, 18)
                        .addComponent(a2Btn5)
                        .addGap(18, 18, 18)
                        .addComponent(a3Btn5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a4Btn5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q6Lbl)
                            .addComponent(q7Lbl))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a1Btn6)
                            .addComponent(a1Btn7)
                            .addComponent(a1Btn8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a2Btn6)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a4Btn6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a2Btn7)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a4Btn7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a2Btn8)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a4Btn8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q10Lbl)
                            .addComponent(q9Lbl))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn10)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3Btn10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1Btn9)
                                .addGap(18, 18, 18)
                                .addComponent(a2Btn9)
                                .addGap(18, 18, 18)
                                .addComponent(a3Btn9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a4Btn9)
                            .addComponent(a4Btn10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(titleLbl))
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(feedBackFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q1Lbl)
                            .addComponent(a1Btn1)
                            .addComponent(a2Btn1)
                            .addComponent(a3Btn1)
                            .addComponent(a4Btn1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2Lbl)
                            .addComponent(a1Btn2)
                            .addComponent(a2Btn2)
                            .addComponent(a3Btn2)
                            .addComponent(a4Btn2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3Lbl)
                            .addComponent(a1Btn3)
                            .addComponent(a2Btn3)
                            .addComponent(a3Btn3)
                            .addComponent(a4Btn3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4Lbl)
                            .addComponent(a1Btn4)
                            .addComponent(a2Btn4)
                            .addComponent(a3Btn4)
                            .addComponent(a4Btn4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5Lbl)
                            .addComponent(a1Btn5)
                            .addComponent(a2Btn5)
                            .addComponent(a3Btn5)
                            .addComponent(a4Btn5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q6Lbl)
                            .addComponent(a1Btn6)
                            .addComponent(a2Btn6)
                            .addComponent(a3Btn6)
                            .addComponent(a4Btn6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(q7Lbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a1Btn7)
                                    .addComponent(a2Btn7)
                                    .addComponent(a3Btn7)
                                    .addComponent(a4Btn7))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q8Lbl)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a1Btn8)
                                .addComponent(a2Btn8)
                                .addComponent(a3Btn8)
                                .addComponent(a4Btn8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(q9Lbl)
                                .addGap(31, 31, 31)
                                .addComponent(q10Lbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a1Btn9)
                                    .addComponent(a2Btn9)
                                    .addComponent(a3Btn9)
                                    .addComponent(a4Btn9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a1Btn10)
                                    .addComponent(a2Btn10)
                                    .addComponent(a3Btn10)
                                    .addComponent(a4Btn10)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(feedBackFeild)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn1ActionPerformed

    private void a1Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn6ActionPerformed

    private void a1Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1Btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1Btn7ActionPerformed

    /**
     * Go back to the main menu
     *
     * @param evt
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        // Create Quiz Window
        //Quiz window frame is now visible
        mainMenuWindow.setVisible(true);

        //Set This Window to not be visible
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * Method that handles the output of the questions for each row
     */
    public void writeQuestion() {
        //Getting the data from the file
        ArrayList<Question> data = DataLoader.readQuestions();

        //Store a shallow copy of the buttons in an arraylist
        ArrayList<javax.swing.JLabel> questionLabels = new ArrayList<>(Arrays.asList(q1Lbl, q2Lbl, q3Lbl, q4Lbl, q5Lbl, q6Lbl, q7Lbl, q8Lbl, q9Lbl, q10Lbl));

        //Save all the questions in an arraylist
        for (int i = 0; i < data.size(); i++) {
            //Store the question to be written
            String question = data.get(i).getQuestion();

            //Write the question
            questionLabels.get(i).setText(question);
        }
    }
    
    /**
     * Method that handles the output of the radio buttons with a semi random order
     */
    public void writeAnswer() {
        //Getting the data from the file
        ArrayList<Question> data = DataLoader.readQuestions();

        //2d Arraylist for the radio button options
        ArrayList<ArrayList<javax.swing.JRadioButton>> radioButtons = new ArrayList<>(Arrays.asList(new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn1, a2Btn1, a3Btn1, a4Btn1)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn2, a2Btn2, a3Btn2, a4Btn2)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn3, a2Btn3, a3Btn3, a4Btn3)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn4, a2Btn4, a3Btn4, a4Btn4)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn5, a2Btn5, a3Btn5, a4Btn5)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn6, a2Btn6, a3Btn6, a4Btn6)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn7, a2Btn7, a3Btn7, a4Btn7)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn8, a2Btn8, a3Btn8, a4Btn8)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn9, a2Btn9, a3Btn9, a4Btn9)), new ArrayList<javax.swing.JRadioButton>(Arrays.asList(a1Btn10, a2Btn10, a3Btn10, a4Btn10))));

        //Loop for each question
        for (int i = 0; i < data.size(); i++) {
            //Get a random number
            int random = randomNum(1, 4);

            //Assign the true answer semi randomly to a radio button
            switch (random) {
                case 1:
                    radioButtons.get(i).get(0).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(1).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(2).setText(data.get(i).getPossibleAns3());
                    radioButtons.get(i).get(3).setText(data.get(i).getTrueAns());
                    break;
                case 2:
                    radioButtons.get(i).get(0).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(1).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(2).setText(data.get(i).getTrueAns());
                    radioButtons.get(i).get(3).setText(data.get(i).getPossibleAns3());
                    break;
                case 3:
                    radioButtons.get(i).get(0).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(1).setText(data.get(i).getTrueAns());
                    radioButtons.get(i).get(2).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(3).setText(data.get(i).getPossibleAns3());
                    break;
                case 4:
                    radioButtons.get(i).get(0).setText(data.get(i).getTrueAns());
                    radioButtons.get(i).get(1).setText(data.get(i).getPossibleAns1());
                    radioButtons.get(i).get(2).setText(data.get(i).getPossibleAns2());
                    radioButtons.get(i).get(3).setText(data.get(i).getPossibleAns3());
                    break;
                default:
                    break;
            }

        }
    }

    private int randomNum(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1Btn1;
    private javax.swing.JRadioButton a1Btn10;
    private javax.swing.JRadioButton a1Btn2;
    private javax.swing.JRadioButton a1Btn3;
    private javax.swing.JRadioButton a1Btn4;
    private javax.swing.JRadioButton a1Btn5;
    private javax.swing.JRadioButton a1Btn6;
    private javax.swing.JRadioButton a1Btn7;
    private javax.swing.JRadioButton a1Btn8;
    private javax.swing.JRadioButton a1Btn9;
    private javax.swing.JRadioButton a2Btn1;
    private javax.swing.JRadioButton a2Btn10;
    private javax.swing.JRadioButton a2Btn2;
    private javax.swing.JRadioButton a2Btn3;
    private javax.swing.JRadioButton a2Btn4;
    private javax.swing.JRadioButton a2Btn5;
    private javax.swing.JRadioButton a2Btn6;
    private javax.swing.JRadioButton a2Btn7;
    private javax.swing.JRadioButton a2Btn8;
    private javax.swing.JRadioButton a2Btn9;
    private javax.swing.JRadioButton a3Btn1;
    private javax.swing.JRadioButton a3Btn10;
    private javax.swing.JRadioButton a3Btn2;
    private javax.swing.JRadioButton a3Btn3;
    private javax.swing.JRadioButton a3Btn4;
    private javax.swing.JRadioButton a3Btn5;
    private javax.swing.JRadioButton a3Btn6;
    private javax.swing.JRadioButton a3Btn7;
    private javax.swing.JRadioButton a3Btn8;
    private javax.swing.JRadioButton a3Btn9;
    private javax.swing.JRadioButton a4Btn1;
    private javax.swing.JRadioButton a4Btn10;
    private javax.swing.JRadioButton a4Btn2;
    private javax.swing.JRadioButton a4Btn3;
    private javax.swing.JRadioButton a4Btn4;
    private javax.swing.JRadioButton a4Btn5;
    private javax.swing.JRadioButton a4Btn6;
    private javax.swing.JRadioButton a4Btn7;
    private javax.swing.JRadioButton a4Btn8;
    private javax.swing.JRadioButton a4Btn9;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField feedBackFeild;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup q10Group;
    private javax.swing.JLabel q10Lbl;
    private javax.swing.ButtonGroup q1Group;
    private javax.swing.JLabel q1Lbl;
    private javax.swing.ButtonGroup q2Group;
    private javax.swing.JLabel q2Lbl;
    private javax.swing.ButtonGroup q3Group;
    private javax.swing.JLabel q3Lbl;
    private javax.swing.ButtonGroup q4Group;
    private javax.swing.JLabel q4Lbl;
    private javax.swing.ButtonGroup q5Group;
    private javax.swing.JLabel q5Lbl;
    private javax.swing.ButtonGroup q6Group;
    private javax.swing.JLabel q6Lbl;
    private javax.swing.ButtonGroup q7Group;
    private javax.swing.JLabel q7Lbl;
    private javax.swing.ButtonGroup q8Group;
    private javax.swing.JLabel q8Lbl;
    private javax.swing.ButtonGroup q9Group;
    private javax.swing.JLabel q9Lbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
