/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectmanagment;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author yuzha3124
 */
public class StudyNote extends javax.swing.JFrame {

    ProjectManagment firstWindow;

    /**
     * Creates new form StudyNote
     * @param m
     */
    public StudyNote(ProjectManagment m) {
        initComponents();
        firstWindow = m;
        lblNote.setText(readFile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmGoback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmGoback.setText("Click to go back to quiz window");
        btmGoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmGobackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Study Note");

        lblNote.setText("text here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btmGoback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNote)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btmGoback)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNote)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String readFile() {
        String msg = "";
        int count = 0;
        try { //to open the file
            File f = new File("src/projectmanagment/questions.txt"); //create a link to the external file
            Scanner s = new Scanner(f); //attach a scanner
            //repeat for each element in the array
            while(s.hasNextLine()){
                count++;
                if (count == 6){
                    msg += "\n" + s.nextLine();
                }
            }
        } catch (FileNotFoundException e) { //runs if the file is not found
            System.out.println(e);
        }
        
        return msg;
    }
    private void btmGobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmGobackActionPerformed
        // button for going back to quiz window
        firstWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmGobackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmGoback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNote;
    // End of variables declaration//GEN-END:variables
}
